const routes = {
  register: "Register",
  login: "Login",
  splash: "Splash",
  dashboard: "Dashboard",
  createEnvelope: "CreateEnvelope",
  Subscriptions: "Subscriptions",
  signEnvelope: "SignEnvelope",
  viewEnvelope: "ViewEnvelope",
  Manage: "Manage",
  Settings: "Settings",
  TemplateDocument: "TemplateDocument",
  Plans: "Plans",
  Checkout: "Checkout",
  StripeCheckout: "StripeCheckout",
  ForgotPassword: "ForgotPassword",
  Address: "Address",
  Teams: "Teams",
  ViewTeam: "ViewTeam",
};
export default routes;
